### PR TITLE
Fix appendTab for empty tabsetPanels

### LINKED ISSUE #1812: append/prependTab issue when no existing tabs
I just tried using appendTab to dynamically add tabPanels but it always displays the content of the first added tabPanel. The prepend has the same issue.

@wch pointed out that this issue is due to no existing tabs before calling appendTab

```R
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton("add", "Add 'Dynamic' tab")
    ),
    mainPanel(
      tabsetPanel(id = "tabs")
    )
  )
)

server <- function(input, output) {
  
  observeEvent(input$add, {
    appendTab(
      inputId = "tabs",
      tab = tabPanel("Dynamic", paste("This a dynamically-added tab", input$add)),
      select = TRUE
    )
  })
}

shinyApp(ui, server)
```

### PR DESCRIPTION
**Pull request by bborgesr**
Fixes #1812.

In addition, I opted for using ES6's [spread operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator) to do `Math.max(...existingTabIds) + 1` instead of `Math.max(0, Math.max.apply(null, existingTabIds) + 1)` 

**5min later update:** 
I remembered [there are non-cutting edge browsers](http://kangax.github.io/compat-table/es6/#test-spread_(...)_operator) and I reverted back to the much safer `Math.max.apply(null, existingTabIds) + 1;`

---

I also changed the initialization of `existingTabIds` from `var existingTabIds = [];` to `var existingTabIds = [0];` in order to be explicit about the edge case -- added an explanatory comment as well.

Finally, I was able to get grunt to work, but a simple upgrade did the trick, and I assume it's good for us to have the dependencies up to date anyway, so I didn't try to revert back.

Here's my output before and after the update when I enter the `grunt` command:

```sh
Barbaras-MacBook-Pro:tools barbaraborges$ grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
Barbaras-MacBook-Pro:tools barbaraborges$ yarn add --dev grunt
yarn add v0.17.8
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "grunt@>= 0.4.5".
warning Unmet peer dependency "grunt@>=0.4.0".
warning Unmet peer dependency "grunt@>=0.4.0".
warning Unmet peer dependency "grunt@>=0.4.1".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ grunt@1.0.1
warning No license field
✨  Done in 10.17s.
Barbaras-MacBook-Pro:tools barbaraborges$ grunt
Running "newer:concat" (newer) task

Running "newer:concat:shiny" (newer) task

... etc etc etc
```

### CODE REVIEW

**Comment by wch** [comment]
Does this also fix the behavior for `prependTab`?

**Comment by bborgesr** [comment]
@wch: Yes

**Comment by jcheng5** [comment]
Regarding that grunt error message, I believe a `yarn install` would also have fixed it. At least, that's been the case for me whenever I've gotten that error--it usually meant I didn't have node_modules at all.

**Comment by panoptikum** [comment]
Have you tested this fix within a module as well? I can append tabs, if the panel is not empty, but the same code does not work when the panel is empty. But maybe my code is not written properly...

**Comment by bborgesr** [comment]
Yes, this also works for modules. If you have a reproducible example of what you mention, we can take a look since that seems odd.

However, here is a simple example to show that this works:

```r
modUI <- function(id) {
  ns <- NS(id)

  sidebarLayout(
    sidebarPanel(
      actionButton(ns("add"), "Add 'Dynamic' tab")
    ),
    mainPanel(
      tabsetPanel(id = ns("tabs"))
    )
  )
}

mod <- function(input, output, session) {
  observeEvent(input$add, {
    appendTab(
      inputId = "tabs",
      tab = tabPanel(paste("Dynamic", input$add), paste("This a dynamically-added tab", input$add)),
      select = TRUE
    )
  })
}


ui <- fluidPage(
  modUI("tabs")
)

server <- function(input, output) {
  callModule(mod, "tabs")
}

shinyApp(ui, server)
```

**Pull request merged**
