### PR TITLE
Support reading of Shiny outputs

### PR DESCRIPTION
**Pull request by jcheng5**
Until now, you've been able to assign to the `output` object (i.e. `output$table <- renderTable(...)`) but we throw an error if you try to read from it (i.e. `print(output$plot)`). The reason for this is because I didn't want Shiny beginners to think they could read the current plot.

However, with shinymeta we now have a need for reading outputs. Although shinymeta enables an important scenario, this is admittedly a pretty advanced, niche use; so this PR adds the functionality, but you have to enable it with a global option `shiny.allowoutputreads` (undocumented for now).

I've implemented this as an R option instead of a `shinyOption` because we explicitly do not want to tie the lifetime of the option to an app, but instead to the R process lifetime (I am setting this option in shinymeta's `.onLoad`).

### CODE REVIEW

**Comment by jcheng5** [comment]
@wch Can I ask you to take a look at this early next week? I'd love to have it merged to master before useR so shinymeta can stop relying on a specific Shiny branch.

**Comment by wch** [comment]
One more thought: it would be good to document `shiny.allowoutputreads` in the `shiny-options` help page.

**Comment by jcheng5** [comment]
@wch Would it be bad to keep it undocumented? 😬 I couldn't think of a legitimate use for this outside of shinymeta.

**Comment by wch** [comment]
Well, we do have other weird things documented there which no one should normally use... But if you feel strongly about it, I'm OK with not documenting it.

**Pull request merged**
