### PR TITLE
Allow to create progress bar without a close button

### LINKED ISSUE #2979: Progress with 'closeButton' option
How can I hide the little `x` in progress bar? Some of my users think by clicking `x`, they could interrupt current R, but it's just hiding the UI element.
image

### PR DESCRIPTION
**Pull request by ColinFay**
will close #2979

Demo apps:

```r
system("cd tools && yarn build")
pkgload::load_all()

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    withProgress(
      closeButton = FALSE, 
      message = 'Calculation in progress',
      detail = 'This may take a while...', 
      value = 0, 
      {
        for (i in 1:15) {
          incProgress(1/15)
          Sys.sleep(0.25)
        }
      }
    )
    plot(cars)
  })
}

shinyApp(ui, server)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    progress <- Progress$new(session, min=1, max=15, closeButton = FALSE)
    on.exit(progress$close())
    
    progress$set(message = 'Calculation in progress',
                 detail = 'This may take a while...')
    
    for (i in 1:15) {
      progress$set(value = i)
      Sys.sleep(0.5)
    }
    plot(cars)
  })
}

shinyApp(ui, server)

```

### CODE REVIEW

**Comment by ColinFay** [comment]
@schloerke any reason for closing this PR?

**Comment by schloerke** [comment]
@ColinFay I believe this was an automated action by GitHub.

Re-opening and setting the base branch to `main`

**Comment by schloerke** [comment]
@ColinFay I can not manually point the merge branch. Do you mind resubmitting the PR? Sorry for the hassle

**Comment by ColinFay** [comment]
Ah, i just noticed you've deleted the master branch. I seem to remember that if you delete a branch, all PR to that branch are automatically closed 🤔 

I've been bitten by this before when accidentally deleting a dev branch 😅 

will redo the PR

**Pull request closed without merging**
