### PR TITLE
Add plot interactions with ggplot2

### PR DESCRIPTION
**Pull request by wch**
This adds plot interactions with plots generated by ggplot2, including facets. Also:

* Brushing is scale-aware in base and ggplot graphics. This means that if you send an updated plot with new bounds, the brush can change is pixel coordinates to preserve the same data coordinates.
* Brushes can now be resized.
* I moved `renderPlot()` out of `shinywrappers.R` into its own file, `render-plot.R`. It might be a good idea to move other render functions to their own files as well, but that can be done in a separate PR.

Demo at: https://winston.shinyapps.io/interactive_graphic

### CODE REVIEW

**Comment by josiekre** [comment]
Is your demo code available? I'm hoping to play around with your forked version to test out the hovering and click functionality.

**Comment by wch** [comment]
@josiekre Here's the code for the demo: https://gist.github.com/wch/babeea49b39847608de3

**Comment by wch** [comment]
I think this PR should be ready to merge now.

**Comment by jcheng5** [comment]
Nice. I'll review tomorrow.

**Comment by wch** [comment]
I've addressed the issues we discussed, so this should be ready to merge.

**Comment by jcheng5** [comment]
Congratulations! :clap: 

Can you update NEWS on master? I bumped the version already.

**Pull request merged**
