### PR TITLE
Fix #1438: `unbindAll()` should not be called when inserting content with `insertUI()`

### LINKED ISSUE #1438: insertUI bindAll scope should behave better for interactive outputs
See rstudio/DT#369.

We'll have to rework this somewhow: https://github.com/rstudio/shiny/blob/master/srcjs/output_binding_html.js#L47

### PR DESCRIPTION
**Pull request by bborgesr**
It seems like this one was pretty painless!

### CODE REVIEW

**Comment by jcheng5** [comment]
@happyshows Do you mind installing this branch and testing your app against it? This seems like a pretty safe change, but I feel like if it's going to break anyone's app, it'll be yours :)

**Comment by jcheng5** [comment]
LGTM though.

**Comment by jcheng5** [comment]
LGTM though.

**Comment by wch** [comment]
Regarding moving some of the items into the "Bug fixes" section: some of them aren't actually bug fixes even though they start with "Fixed". They were new features (added by Dean).

**Comment by happyshows** [comment]
@jcheng5  I just joined another company and cannot test my original code at the moment, will get back to you once I have time to test it out. Let's close this for now and re-open if necessary.

**Comment by bborgesr** [comment]
@wch: I've spoken to Joe and he's okay with us merging this, as any problem that this change may give rise to, we will likely not find it by inspection. The only reason I'm not merging this myself right now is that I had to do a git rebase to get this branch up-to-date and I'd feel happier if you were the one merging, in case I accidentally messed up the rebase (getting better at that though, I hope!)

**Pull request merged**
