### PR TITLE
Update htmlTemplate docs for htmltools 0.3.5

### PR DESCRIPTION
**Pull request by jcheng5**
I'm seeing a different failure locally, something relating to ggplot2.

### CODE REVIEW

**Comment by jcheng5** [comment]
@wch, aee5bda9ec4ee4ccdfcde0fa10eeafe9a446295e seems to have broken some unit tests, at least on my machine.

**Comment by jcheng5** [comment]
```
1. Error: ggplot coordmap ------------------------------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: expect_equal(m[[1]]$mapping, list(x = "xvar", y = "yvar")) at test-plot-coordmap.R:34
5: expect_that(object, equals(expected, label = expected.label, ...), info = info, label = label)
6: condition(object)
7: compare(actual, expected, ...)

2. Failure (at test-plot-coordmap.R#80): ggplot coordmap with facet_wrap -------
length(m) not equal to 3
0 - 3 == -3

3. Error: ggplot coordmap with facet_wrap --------------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: expect_equal(m[[1]]$panel, 1) at test-plot-coordmap.R:81
5: expect_that(object, equals(expected, label = expected.label, ...), info = info, label = label)
6: condition(object)
7: compare(actual, expected, ...)

4. Failure (at test-plot-coordmap.R#129): ggplot coordmap with facet_grid ------
length(m) not equal to 3
0 - 3 == -3

5. Error: ggplot coordmap with facet_grid --------------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: expect_equal(m[[1]]$panel, 1) at test-plot-coordmap.R:130
5: expect_that(object, equals(expected, label = expected.label, ...), info = info, label = label)
6: condition(object)
7: compare(actual, expected, ...)

6. Failure (at test-plot-coordmap.R#214): ggplot coordmap with 2D facet_grid ---
length(m) not equal to 4
0 - 4 == -4

7. Error: ggplot coordmap with 2D facet_grid -----------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: expect_equal(m[[1]]$panel, 1) at test-plot-coordmap.R:215
5: expect_that(object, equals(expected, label = expected.label, ...), info = info, label = label)
6: condition(object)
7: compare(actual, expected, ...)

8. Failure (at test-staticdocs.R#27): All man pages have an entry in staticdocs/index.r
length(missing) not equal to 0
1 - 0 == 1
Functions missing from index:
  cancelOutput
Warning message:
package ‘ggplot2’ was built under R version 3.2.4
```

**Comment by bborgesr** [comment]
I get the same errors on my machine as @jcheng5

**Comment by jcheng5** [comment]
This is on Mac, BTW.

**Comment by wch** [comment]
I think this also needs a version dependency bump for htmltools in the DESCRIPTION file. I'll look into the ggplot2 thing.

**Comment by wch** [comment]
I've pushed a fix for the coordmap tests and I incremented the htmltools version (so that the documentation for the `htmlTemplate` args will match the actual function signature) in this branch. It should be good to merge.

**Pull request merged**
