### PR TITLE
bindCache() docs typos

### PR DESCRIPTION
**Pull request by nstrayer**
Just a couple tiny typos I noticed while reading the `bindCache()` docs.

### CODE REVIEW

**Review by wch — APPROVED** [review]
Looks good! Please re-run `devtools::document()` before merging.

**Comment by wch** [comment]
There are a lot of spurious changes in the .Rd files. Are you using the latest version of roxygen2?

**Comment by nstrayer** [comment]
I guess I did. Sorry about that. Fixed with the latest cran version of `roxygen2.` Only non `bindCache()` related docs that are now modified is `plotPNG()` where a cairo link got updated. I can remove that as well if desired.

**Comment by wch** [comment]
Do you have the Cairo package installed? It might need it to properly resolve the documentation link.

**Review by wch — APPROVED** [review]

**Pull request merged**
