### PR TITLE
Tweak startup message

### PR DESCRIPTION
**Pull request by hadley**
* Specifically mention shiny
* Eliminate leading newline
* Tell the user how to stop it

I _think_ this will help new users, and experienced users will rapidly not see it because they see it so frequently.

### CODE REVIEW

**Comment by wch** [comment]
This will break shinytest because it looks for `"Listening on http"`: https://github.com/rstudio/shinytest/blob/400ff15072d5fa2ab8b380b4436d1fc65308a3f4/R/initialize.R#L152

We can make shinytest also look for the new message, but I think we should hold off merging this  until an updated release of shinytest has been out for a while.

**Comment by jcheng5** [comment]
@hadley How about we keep the `messageStopApp` behavior but leave the startup messages alone?

**Comment by hadley** [comment]
What if we made it `Shiny: Listening on ...`? 

Alternatively, it could condition of the version of shinytest, if it's installed.

**Comment by hadley** [comment]
Should I bring this up to date or kill it?

**Comment by wch** [comment]
@jmcphers Will this change cause issues with running Shiny apps in the IDE?

**Comment by jmcphers** [comment]
Not for regular Shiny in-proc apps (I think we pass our own "browser") to make that robust, but it would break Shiny R Markdown docs.

https://github.com/rstudio/rstudio/blob/bf728258a8061322641bfd5f2548723064f5ecc9/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L612

**Comment by wch** [comment]
I think we should close -- I don't think the benefit is worth the trouble it would cause.

Thanks, @jmcphers!

**Pull request closed without merging**
