### PR TITLE
Barbara/improve news

### PR DESCRIPTION
**Pull request by bborgesr**
Change the NEWS.md to have a more Release Notes-type role.

### CODE REVIEW

**Comment by wch** [comment]
@bborgesr This might be useful: https://jbt.github.io/markdown-editor/

**Comment by bborgesr** [comment]
Thanks, @wch, I'll certainly try to work with a tool like that in the future... 
But unfortunately, there are still some discrepancies. For example, GFM rendered *in* GH will be stripped by the `style` tags and attributes, so this:

```html
<style>
h1 {color:red;}
p {color:blue;}
</style>
```

is rendered as plain text in GH:
```
h1 {color:red;}
p {color:blue;}
```

But it works as it was meant to in the editor you sent me... :( Plus, I wanted to avoid having to copy paste stuff in order to test it in one place and commit/push it in another place...

I apologize for subjecting you all to an unfiltered look at the brain trying to make things work...

**Comment by jcheng5** [comment]
LGTM! Watch out for Winston's modification(s?) to NEWS.md on master.

**Comment by bborgesr** [comment]
Up-to-date with Winston's additions to NEWS on master, as of now. This is probably good to merge, but maybe we could spend 5 min on this tomorrow? I know @wch wasn't really feeling the reference-style links at the top and it may be good to chat anyway about the doc, the level of detail etc... (also, how we're going to deal with the equivalent of this on the website, though I suppose we can merge and then worry about that).

**Comment by wch** [comment]
Squash-merged in 259b4e2.

**Pull request closed without merging**
