### PR TITLE
Improving sliderInput accessibility

### PR DESCRIPTION
**Pull request by jooyoungseo**
This draft attempts to address #2845 (sliderInput accessibility) and it is still under development.

## To-Do List

- [ ] Patch `IonRangeSlider.js` to not set `tabindex` to "-1": We need to fix this to `tabindex` = "0" to allow keyboard tabbing focus.
- [ ] Write a patch js to slider value changes to be announced to screen readers: see [Deque University](https://dequeuniversity.com/library/aria/slider) and [aria practice](https://www.w3.org/TR/wai-aria-practices-1.1/examples/slider/slider-1.html).

### CODE REVIEW

**Comment by itsozz** [comment]
When testing this widget using [WAVE](https://wave.webaim.org) "_very low contrast_" errors and "_small text_" alerts are reported. The small text alerts are reported for all elements except the current slider value(s) displayed above the 'thumb' control(s) and the very low contrast errors are for all. The number of errors and alerts reported depends on whether you have the grid number markings displayed or not, and if so - how many there are.

I've used the following CSS to overcome these issues. (NOTE: although the slider bar colour doesn't cause an error, I've changed it to maintain consistency with the current slider value(s) background which does require modification.)

```css
/* slider scale, min and max numbers */
.irs-grid-text, .irs-min, .irs-max {
    color: #333;
    font-size: 0.8em;
}   
                               
/* value(s) of slider appearing above the 'thumb' control(s) */
.irs-from, .irs-to, .irs-single {
    background-color: #5d77a3;
    color: #fff;
}
                               
/* slider highlighted/filled range */
.irs-bar, .irs-bar-edge {
    background-color: #5d77a3;
}
```

**Comment by sasscal-dwd-apps** [comment]
Dear Developers,
I am also very interested on this topic, since I am developing different Apps with Shiny, and they all should be "accessible". I was also trying to use "noUISliderInput" instead of "sliderInput", but it is also inaccessible with the keyboard (at least using "tab")
Looking forward to seeing the solution on this issue.

**Comment by cpsievert** [comment]
I'll take this over the finish line in #3011, thanks @jooyoungseo!

**Comment by tpetzoldt** [comment]
I came across the same problem (keyboard accessibility of sliderInput) and tested it again right now, so I want to ask if there was any progress in the meantime. Thanks!

**Pull request closed without merging**
