### PR TITLE
v1.7.5.1 release candidate

### LINKED ISSUE #3911: Release shiny 1.7.6
Prepare for release:

* [ ] `git pull`
* [ ] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_shiny.html)
* [ ] Bump required R version in DESCRIPTION to 3.6
* [ ] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [ ] `urlchecker::url_check()`
* [ ] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()`
* [ ] `revdepcheck::cloud_check()`
* [ ] Update `cran-comments.md`
* [ ] `git push`
* [ ] Update static imports: `staticimports::import()`

Submit to CRAN:

* [ ] `usethis::use_version('patch')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #3911.

This patch release branches off the `v1.7.5` tag to only include #3908  (because CRAN has requested a fix by Oct 14 and we're not in a position to release the rest of what's on `main`).

### CODE REVIEW

**Comment by cpsievert** [comment]
Note that [837307f](https://github.com/rstudio/shiny/pull/3910/commits/837307fe8cd17641df0b23866ae4c49a5e7f702c) has a false positive error because the routine is being overly opinionated about using `-alpha` in the `package.json` (npm doesn't support 2 digits, so a `-` must be used, but `-alpha` is not required, and since this is an official release, we really shouldn't be including `-alpha` in the version)

**Comment by rhenkin** [comment]
Hi, do you have any updates on this? I have a package that calls isTruthy and that will be removed from CRAN tomorrow, but if this goes through I won't need to change anything (possibly just re-submit if they don't accept the new shiny version on time).

Thanks,
Rafael

**Comment by wch** [comment]
We submitted it to CRAN a week ago, and their automatic reverse dependency checks had an error in the vignette for a package. I think that error had nothing to do with Shiny, and I emailed CRAN twice about it, but still haven't heard back from them.

**Comment by wch** [comment]
This is the relevant part of the email from CRAN:

```
CRAN teams' auto-check service
Package check result: OK

Changes to worse in reverse depends:

Package: hyd1d
Check: re-building of vignette outputs
New result: ERROR
  Error(s) in re-building vignettes:
    ...
  --- re-building ‘hyd1d.Rmd’ using rmarkdown
  --- finished re-building ‘hyd1d.Rmd’

  --- re-building ‘vignette_DE.Rmd’ using rmarkdown

  Quitting from lines 1165-1190 [figure15] (vignette_DE.Rmd)
  Error: processing vignette ‘vignette_DE.Rmd’ failed with diagnostics:
  the condition has length > 1
  --- failed re-building ‘vignette_DE.Rmd’

  SUMMARY: processing the following file failed:
    ‘vignette_DE.Rmd’

  Error: Vignette re-building failed.
  Execution halted
```

The error is apparently from this code block:
https://github.com/bafg-bund/hyd1d/blob/release-v0.4.6/vignettes/vignette_DE.Rmd#L1165-L1189

**Comment by gadenbuie** [comment]
@wch I installed r-devel (latest available via `rig` was `2023-10-09 r85295`) and using this version of Shiny, I could not reproduce the problem.

However! I noticed that the functions in that vignette collect data from remote online resources. By disconnecting my computer from the internet, I **was** able to reproduce the exact error, and the output gives a little more context:

```
> rmarkdown::render("vignettes/vignette_DE.Rmd")


processing file: vignette_DE.Rmd
  |...                                      |   8% [captions]                  curl: (6) Could not resolve host: hyd1d.bafg.de
  |.................................        |  79% [figure15]
Quitting from lines 1165-1190 [figure15] (vignette_DE.Rmd)
Error in `if (length(s_gauging_stations_missing) == 1 & is.na(s_gauging_stations_missing)) ...`:
! the condition has length > 1
Backtrace:
 1. base::summary(wldf)
 2. hyd1d:::summary.WaterLevelDataFrame(wldf)
```

**Comment by wch** [comment]
@rhenkin Shiny 1.7.5.1 is on CRAN now, so you should be good to go.

**Comment by cpsievert** [comment]
@wch this PR is mergeable now -- I think we'll want to do a merge commit (not squash+merge) so that the v1.7.5.1 tag ([837307f](https://github.com/rstudio/shiny/pull/3910/commits/837307fe8cd17641df0b23866ae4c49a5e7f702c)) gets properly included into `main`'s history?

Also, it appears the routine failure in [481a692](https://github.com/rstudio/shiny/pull/3910/commits/481a692b07b3407ff67a88cd0c57dbda8ddd955a) is, again, due to shiny-workflows wanting to use the `rc-v*` branch name to inform the version

**Comment by wch** [comment]
Yes, I think we're good to merge this now.

One thing that I'm a little confused by is that the Files Changed view in this PR only shows that the NEWS.md file has changed. Is that because main also contained the fix, and main was merged in to this branch?

**Comment by cpsievert** [comment]
> Is that because main also contained the fix, and main was merged in to this branch?

Yep, this PR started by branching off of the `v1.7.5` tag to only include essentially the latest commit to main. And now that it's been merged with main, the only changes should be to the `NEWS.md`

**Pull request merged**
