### PR TITLE
Add domain context to session$onSessionEnded callbacks

### PR DESCRIPTION
**Pull request by schloerke**
This PR changes the callback execution context from "_some_ session ended" to "**this** session ended".

### Test File

`./onSessionEnded.R`
```r
library(shiny)

ui <- fluidPage(
  HTML("
  Reprex:<br>
  * Close window (if it doesn't auto close)<br>
  * Verify session token exists in console<br>
  "),
  tags$script("setTimeout(window.close, 3000);")
)

defined_with_no_session_context <- function() {
  message("Ended! Domain length: ", length(getDefaultReactiveDomain()))
  message("Ended! Token: ", getDefaultReactiveDomain()$token)
}

server <- function(input, output, session) {
  session$onSessionEnded(defined_with_no_session_context)
}

shinyApp(ui, server)
```

### Before PR

The `getDefaultReactiveDomain()` object does not exist.

```r
shiny::shinyAppFile("onSessionEnded.R")
#>
#> Listening on http://127.0.0.1:6026
#> Ended! Domain length: 0
#> Ended! Token: 
```

### After PR

The `getDefaultReactiveDomain()` object exists.

```r
shiny::shinyAppFile("onSessionEnded.R")
#>
#> Listening on http://127.0.0.1:3469
#> Ended! Domain length: 84
#> Ended! Token: bf248258f2896ba8e1ad08debf2b73c9
```

----------------------------

cc @trestletech @alandipert

### CODE REVIEW

**Comment by jcheng5** [comment]
With this change, do all of the `session$onXXX` callbacks now have `withReactiveDomain`?

**Comment by trestletech** [comment]
Is it possible to bump the version alongside this change so we can detect whether or not this feature is expected to work?

**Comment by schloerke** [comment]
@jcheng5 No. I don't think so.  I'll look into it some more.

@trestletech Can do.

**Comment by schloerke** [comment]
@jcheng5 

Fixed in this PR: 
* onSessionEnded

Previously working:
* `onInputReceived`
* `onBookmark`
* `onBookmarked`
* `onRestore`
* `onRestored`
* `onFlush`
* `onFlushed`


### Test file:
`./onSessionEnded.R`
```r
library(shiny)

# Fixes:
# * onSessionEnded

if (FALSE) {
  # * Triggers onRestore, onRestored
  later::later(delay = 2, function() { browseURL("http://127.0.0.1:8000?_inputs_&num=5"); });  shiny::shinyAppFile("./onSessionEnded.R", options = list(port = 8000, launch.browser = FALSE))
}


ui <- function() {
  fluidPage(
    HTML("
    Reprex:<br>
    * Close window (if it doesn't auto close)<br>
    * Verify session token exists in console<br>
    "),
    # default to 1
    numericInput("num", "Number: ", 1),
    # change value to 6 after 3 seconds
    # * Triggers onInputChange
    tags$script('setTimeout(function() { $("#num").val(6).trigger("change") }, 3000);'),


    tags$script("setTimeout(window.close, 5000);"),
    # tags$script("setTimeout(function() {
    #   $('')
    # }, 3000);")
  )
}

defined_with_no_session_context <- function(ctx) {
  function(...) {
    cat("\n\n")
    message(ctx, "! Domain length: ", length(getDefaultReactiveDomain()))
    message(ctx, "! Token: ", getDefaultReactiveDomain()$token)
    message(ctx, "! Parameters:")
    str(list(...))
  }
}

server <- function(input, output, session) {

  session$onSessionEnded(defined_with_no_session_context("onSessionEnded"))
  session$onInputReceived(defined_with_no_session_context("onInputReceived"))
  session$onBookmark(defined_with_no_session_context("onBookmark"))
  session$onBookmarked(defined_with_no_session_context("onBookmarked"))
  session$onRestore(defined_with_no_session_context("onRestore"))
  session$onRestored(defined_with_no_session_context("onRestored"))
  session$onFlush(defined_with_no_session_context("onFlush"), once = FALSE)
  session$onFlushed(defined_with_no_session_context("onFlushed"), once = FALSE)

  observeEvent({input$num}, {
    if (input$num == 6) {
      # * Triggers onBookmark, onBookmarked
      session$doBookmark()
    }
  })

  onSessionEnded(function() {
    # Quit the app if the user closes the window
    stopApp("reject")
  })

}

enableBookmarking(store = "url")
shinyApp(ui, server)
```

### Exec code:

```r
later::later(delay = 2, function() { browseURL("http://127.0.0.1:8000?_inputs_&num=5"); })
shiny::shinyAppFile("./onSessionEnded.R", options = list(port = 8000, launch.browser = FALSE))
```

### Test output

```
Listening on http://127.0.0.1:8000


onRestore! Domain length: 84
onRestore! Token: f25cb9ca8df15c27d40aa44aa34452d8
onRestore! Parameters:
List of 1
 $ :List of 3
  ..$ input :List of 1
  .. ..$ num: int 5
  ..$ dir   : NULL
  ..$ values:<environment: 0x7f9dc7e52980> 


onFlush! Domain length: 84
onFlush! Token: f25cb9ca8df15c27d40aa44aa34452d8
onFlush! Parameters:
 list()


onRestored! Domain length: 84
onRestored! Token: f25cb9ca8df15c27d40aa44aa34452d8
onRestored! Parameters:
List of 1
 $ :List of 3
  ..$ input :List of 1
  .. ..$ num: int 5
  ..$ dir   : NULL
  ..$ values:<environment: 0x7f9dc7e52980> 


onFlushed! Domain length: 84
onFlushed! Token: f25cb9ca8df15c27d40aa44aa34452d8
onFlushed! Parameters:
 list()


onInputReceived! Domain length: 84
onInputReceived! Token: f25cb9ca8df15c27d40aa44aa34452d8
onInputReceived! Parameters:
List of 1
 $ :List of 1
  ..$ num: int 6


onBookmark! Domain length: 84
onBookmark! Token: f25cb9ca8df15c27d40aa44aa34452d8
onBookmark! Parameters:
List of 1
 $ :Classes 'ShinySaveState', 'R6' <ShinySaveState>
  Public:
    clone: function (deep = FALSE) 
    dir: NULL
    exclude: 
    initialize: function (input = NULL, exclude = NULL, onSave = NULL) 
    input: reactivevalues
    onSave: function (state) 
    values: active binding
  Private:
    values_: environment 


onBookmarked! Domain length: 84
onBookmarked! Token: f25cb9ca8df15c27d40aa44aa34452d8
onBookmarked! Parameters:
List of 1
 $ : chr "http://127.0.0.1:8000/?_inputs_&num=6"


onFlush! Domain length: 84
onFlush! Token: f25cb9ca8df15c27d40aa44aa34452d8
onFlush! Parameters:
 list()


onFlushed! Domain length: 84
onFlushed! Token: f25cb9ca8df15c27d40aa44aa34452d8
onFlushed! Parameters:
 list()


onSessionEnded! Domain length: 84
onSessionEnded! Token: f25cb9ca8df15c27d40aa44aa34452d8
onSessionEnded! Parameters:
 list()
```

**Comment by jcheng5** [comment]
Great, thanks @schloerke!

**Comment by alandipert** [comment]
It just occurred to me, maybe these changes should be applied to `MockSession` too?

If `MockSession` had lifecycle callback support, and if the MockSession object had methods for triggering session lifecycle events, user code that did stuff with callbacks could potentially be unit-tested.

**Comment by schloerke** [comment]
Great catch @alandipert !  I'll make it an issue for another day since none of the `MockShinySession` callbacks are invoked with a domain context.  I think that would be too big of change for MockShinySession without thinking about it more.

Side note, any `mockSession$onEnded` callbacks are never called.

**Pull request merged**
