### PR TITLE
New target for `shiny:inputchanged` event

### PR DESCRIPTION
**Pull request by nteetor**
As I mentioned in #2442 the JavaScript Events in Shiny article will need to be updated. Specifically the line below, replacing "document" with "input element".

image

### CODE REVIEW

**Comment by alandipert** [comment]
Thanks for this PR, and for updating the NEWS 👍 I'm not sure I'd categorize the previous behavior as a bug though; how do you feel about listing it under improvements instead?

**Comment by nteetor** [comment]
I wasn't certain either and jumped the gun. I'll move the item under Improvements.

**Comment by alandipert** [comment]
Cool, thanks for switching that up. I noticed also that you don't appear to have sent in a [contributor agreement](https://www.rstudio.com/wp-content/uploads/2014/06/RStudioIndividualContributorAgreement.pdf). If you have, I could be missing something, so please don't hesitate to email me at alan@rstudio.com and we can figure it out.

**Comment by nteetor** [comment]
I sent along the agreement and have moved the news item under improvements.

**Comment by alandipert** [comment]
CA received ✉️ ✅

**Pull request merged**
