### PR TITLE
Add width option to input functions

### LINKED ISSUE #589: width argument of input controls
Hi,

I was wondering why certain input controls have a width element but some obvious others do not? For instance, <code>textInput</code> does not have a width parameter, while <code>selectInput</code> does. Now the only way to increase the width of e.g. <code>textInput</code>  is to add a tag with some css, which is a bit cumbersome.

A similar point can be made for the use of icons i.e. on some buttons they can be added, but on other controls they can't. 

Obviously not big concerns, but it would be nice to have a bit more control over these aspects, it also makes your code more systematic which is always nice. 

kind regards, Herman

### LINKED ISSUE #834: numericInput default width
I know it is simple enough to amend in CSS, but ability to set as a parameter  with default width of 80px would suit me - and I'm guessing many others?

### PR DESCRIPTION
**Pull request by wch**
This closes #589 and closes #834.

I also pulled out all the input functions into separate files, to make them easier to navigate.

Here's a test app:

```R
# Test with a large width; uncomment the second line to use a small width
w <- "90%"
# w <- "150px"

shinyApp(
  ui = bootstrapPage(
    textInput('text', 'textInput', "100", width = w),
    numericInput('numeric', 'numericInput', 100, width = w),
    checkboxInput("checkbox", "checkbox Input", width = w),
    actionButton("action", "actionButton", width = w),
    checkboxGroupInput("checkboxGroup", "checkboxGroupInput",
      c("x asdf asdf asdf asdf asdf" = "x",
        "y fdsa fdsa fdsa fdsa fdsa" = "y"),
      width = w),
    radioButtons("radio", "radioButtons",
      c("x asdf asdf asdf asdf asdf" = "x",
        "y fdsa fdsa fdsa fdsa fdsa" = "y"),
      width = w),
    dateInput("date", "date", value = Sys.Date(), width = w),
    dateRangeInput("daterange", "dateRange", width = w),
    fileInput("file", "fileInput", width = w),
    passwordInput("password", "passwordInput", width = w),
    selectInput("select", "selectInput",
      c("x asdf asdf asdf asdf asdf" = "x",
        "y fdsa fdsa fdsa fdsa fdsa" = "y"),
      width = w, selectize = FALSE),
    selectInput("select2", "selectInput (selectize)",
      c("x asdf asdf asdf asdf asdf" = "x",
        "y fdsa fdsa fdsa fdsa fdsa" = "y"),
      width = w, selectize = TRUE),
    sliderInput("slider", "sliderInput", 0, 100, 50, width = w),
    submitButton("submit", "submitButton", width = w)
  ),
  server = function(input, output) {}
)
```

### CODE REVIEW

**Comment by yihui** [comment]
R CMD check failed as indicated on Travis.

**Comment by wch** [comment]
Oops, fixed.

**Comment by yihui** [comment]
Thanks! On a related note, I guess we could have used `@inheritParams` in many places, since we have a lot of redundant `@param` docs in this package.

**Comment by wch** [comment]
I think we generally did use `@inheritParams` for the input functions... it's just that the `submitButton` is different enough that it didn't have `@inheritParams`. I suppose we could have used it there also.

**Pull request merged**
