### PR TITLE
Add enableBookmarking argument to shinyApp()

### LINKED ISSUE #1312: Add enableBookmarking as an option to shinyApp()
Some of our early testers have requested the ability to do something like `shinyApp(enableBookmarking="url")`.

### PR DESCRIPTION
**Pull request by wch**
This closes #1312. Opinions on the interface? If this looks good, I'll need to make a few more changes to the documentation before we merge.

cc @daattali

### CODE REVIEW

**Comment by daattali** [comment]
Thank you for listening to our feedback, this is much better IMO.  A few small comments that I personally think could be improved:

- I'd think it makes more sense to have the param called `bookmark` or `bookmarking` rather than `enableBookmarking` (shorter, and since it's not a function call then it makes less sense to have it be a verb)
- Is there any reason to include the `disable` option?  If I want it disabled I just won't include the param or set it to NULL, but why would I ever explicitly set it to `disabled`?
- Is it easy to add this param to all the other ways of running a shiny app? For example, on my shiny server I often use `shinyAppDir()` so ideally that function will also take this param (and any other similar functions, I don't know what all the ways are)

**Comment by wch** [comment]
Point taken for the argument name, but after some discussion between me and @jcheng5, we decided to stick with `enableBookmarking`.

For `disable`, that's present for the `enableBookmarking()` function because we want to give people a way to turn it off, if they've turned it on. I think it makes sense to keep the argument the same here. If `NULL` is used here, then it leaves bookmarking unchanged (so a previous `enableBookmarking()` could have an effect).

These are the scenarios that we need to make sure work:
- shinyApp()
  - enableBookmarking()
  - enableBookmarking = "url"
- shinyAppDir()
  - enableBookmarking()
  - enableBookmarking = "url"
- shinyAppFile()
  - enableBookmarking()
  - enableBookmarking = "url"
- runApp() with a directory containing ui.R and server.R
  - enableBookmarking()
- runApp() with a directory containing app.R
  - enableBookmarking()
- runApp() with a list
  - enableBookmarking()

**Comment by daattali** [comment]
Have you considered completely removing the `enableBookmarking()` function that needs to be called independently of a shiny app, and **only** having it as a parameter that is attached to a specific app?

**Comment by wch** [comment]
If you remove `enableBookmarking()`, how would you handle cases where people call `runApp()` in a directory with server.R/ui.R or app.R? We don't want to make bookmarking an argument to `runApp()`; we want to make it something that is a property of the app, not the way that it's invoked.

**Comment by daattali** [comment]
I'm not sure I have a better solution to offer...

> We don't want to make bookmarking an argument to runApp(); we want to make it something that is a property of the app

I agree, but the way it's currently done is *not*  a property of the app, and I do personally think it's safer and more consistent to ask the user to provide it as a param to `runApp()` rather than relying on them to call a function before. 

The best option would be to redesign the implementation so that it doesn't have to be called before the app gets run, and it'll be truly part of the app, that would make it a lot simpler.  But I assume that is out of the question :)

Another random thought I had was "it can be in the DESCRIPTION file" but I haven't seen that file being used much, I feel like it's not something you're really pushing for people to use.

I don't have any more thoughts on the topic, if it remains as it is right now it's good enough for my purposes since I never use runApp, so I won't argue anymore! But it still feel like a very weird interaction to have to call `enableBookmarking()` every time before an app is run

**Comment by wch** [comment]
> I agree, but the way it's currently done is not a property of the app, and I do personally think it's safer and more consistent to ask the user to provide it as a param to runApp() rather than relying on them to call a function before.

But that's not how they are to use it. If they're using `runApp` with an app.R or server.R/ui.R/global.R, then the app author puts `enableBookmarking()` in the app.R or global.R. (Or, with this PR, for app.R, they can use `shinyApp(enableBookmarking = "url")`.)

**Comment by wch** [comment]
This should be good to go now.

After some discussion, @jcheng5  and I decided that `shinyAppDir` and `shinyAppFile` don't need the `enableBookmarking` argument. In both of those cases, the app author has the ability to enable bookmarking in the global.R or app.R, by calling `enableBookmarking()` or `shinyApp(enableBookmarking = X)`.

`shinyApp` has arguments that `shinyAppDir` and `shinyAppFile` don't have, such as `onStart`, so this would be following in that pattern.

**Comment by daattali** [comment]
This will be a bit annoying to use on shiny servers because of https://github.com/rstudio/shiny/issues/1063 since it forces us to put a function in global.R even though global.R isn't recognized when using `shinyAppDir()`.  I guess you can't make everyone happy :)

**Comment by jcheng5** [comment]
Do you mean on shiny server when the app is in a package?

**Comment by daattali** [comment]
Yes that's my main use case, but also any other time when you want to use `shinyAppDir()`.  But yes you're correct, every time somebody asks about how to run an app within a package my answer is to use shinyAppDir() and people generally really like that solution

**Pull request merged**
