### PR TITLE
Allow updateSelectInput(choices=character(0)) to clear select choices

### PR DESCRIPTION
**Pull request by jcheng5**
This is just a strawman proposal. I feel like we have a general problem with ambiguous `NULL` values in update*Input functions.

### CODE REVIEW

**Comment by wch** [comment]
Seems like a good idea to me.

**Comment by jcheng5** [comment]
We could also do `missing()` as the criteria. If you pass `choices=NULL` wouldn't you kind of expect it to be cleared?

**Comment by wch** [comment]
For a short while I used `if(missing())` in some of my code, but I stopped doing it. It works OK for functions that are called interactively at the console, but not so much when your function is called from other functions.

For example:

```R
f <- function(x = NULL) {
  g(x)
}

g <- function(x) {
  if (missing(x)) "x missing"
  else "x present"
}

g(1)
# [1] "x present"
f(1)
# [1] "x present"

g()
# [1] "x missing"
f()
# [1] "x present"
```

**Comment by yihui** [comment]
Using `character(0)` sounds better than `missing()` to me.

**Comment by mcfrank** [comment]
Hi all, just wanted to mention that we are using Shiny - which we love - in a selector-intensive application (wordbank.stanford.edu) and would really like to see this feature merged! Thank you for all your work on this!

**Comment by kevinushey** [comment]
FWIW, I think there was an R bug where `missing` did not return the correct value when called within deeply nested contexts, but I think that should (?) be fixed in current releases of R.

**Comment by wch** [comment]
@mcfrank Glad you guys are making use of Shiny!

@jcheng5 I think this is good to merge, unless you see other issues. We could also implement this for other inputs like radio buttons and checkbox groups.

**Comment by jcheng5** [comment]
Thanks for the tip @kevinushey. Scary.

**Pull request merged**
