### PR TITLE
Update jQuery-UI to 1.13.2

### PR DESCRIPTION
**Pull request by hedsnz**
Addresses #3687 and the associated security fixes.

(I am aware that you do not generally merge PRs for included web libraries.)

### CODE REVIEW

**Comment by dvg-p4** [comment]
BTW if you want to fix that cryptic error, in `package.json` change the line:
`"version": "1.7.2",`
to
`"version": "1.7.2-alpha.9000",`

...or just merge in main, looks like the latest merge fixed that

**Comment by hedsnz** [comment]
@dvg-p4 Sorry, I'm not sure what you mean -- it is already `"version": "1.7.2-alpha.9000",`?

**Comment by dvg-p4** [comment]
...my bad, looks like you're actually having a different problem than I was that's triggering the same cryptic Github Actions error message.

**Review by jcheng5 — APPROVED** [review]

**Comment by schloerke** [comment]
Fixes https://github.com/rstudio/shiny/issues/3687

**Pull request merged**
