### PR TITLE
Add session$onInputReceived

### PR DESCRIPTION
**Pull request by jcheng5**
I added this hook for @joey711 at the rOpenSci hackathon, as it's needed for the reproducibility features of [shiny-phyloseq](http://joey711.github.io/shiny-phyloseq/).

I'm not sure whether we should make this an officially documented hook.

### CODE REVIEW

**Comment by joey711** [comment]
:+1: ! :-)

**Comment by wch** [comment]
Looks reasonable to me... what's the use case for this?

**Comment by joey711** [comment]
Track certain user activities in order to offer the user a reproducible record of the steps they took to get a particular result (usually a graphic).

**Comment by yihui** [comment]
LGTM too.

**Comment by shrektan** [comment]
I love this hook. It helps me to track  the user's activities. :heart:

**Pull request merged**
